-- Generated by HyprMod

-- Settings
hl.config({
    master = {
        orientation = "right",
    },
    misc = {
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
        vrr = 1,
    },
})

-- Monitors
hl.monitor({
    output = "desc:China Star Optoelectronics Technology Co. Ltd 0x150F 0x00005600",
    disabled = false,
    mode = "1920x1080@144.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
