-- Generated by HyprMod

-- Settings
hl.config({
    gestures = {
        workspace_swipe_distance = 100,
        workspace_swipe_min_speed_to_force = 33,
    },
    input = {
        accel_profile = "flat",
        sensitivity = -0.7,
    },
    master = {
        orientation = "right",
    },
    misc = {
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
        vrr = 0,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@144.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
