-- Generated by HyprMod

-- Settings
hl.config({
    dwindle = {
        preserve_split = false,
    },
    general = {
        allow_tearing = false,
    },
    input = {
        accel_profile = "flat",
        sensitivity = 0.0,
    },
    master = {
        orientation = "right",
    },
    misc = {
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
        vrr = 1,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@144.00Hz",
    position = "0x0",
    scale = 0.83,
    cm = "srgb",
})
